name: "Test issue assigned"
on:
    issues:
      types: [opened, edited, assigned]
jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
      - uses: ./
        with:
          github-token: "${{ secrets.MY_NEW_GITHUB_TOKEN_APP }}"