name: "Test issue comments"
on:
  issue_comment:
    types: [created]

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - uses: ./
        with:
          prow-commands: '/assign 
            /done
            /unassign'
          github-token: "${{ secrets.MY_NEW_GITHUB_TOKEN_APP }}"
          # configuration-path: .github/config.yaml
