name: Issue Assigned

on:
  issues:
    types: [ assigned, unassigned ]

jobs:
  checker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run build
      - uses: ./
        with:
          github-token: "${{ secrets.MY_NEW_GITHUB_TOKEN_APP }}"