name: CI

on:
  pull_request:
    types: [ opened, reopened, closed, converted_to_draft]
    branches:
      - 'main'

permissions:
  checks: read
  actions: read

jobs:
  checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install & Build
        run: npm install
             npm run build
      - uses: ./

  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install & Build
        run: npm install
             npm run build
      - uses: ./
        with:
          jobs: 'pr-merged'