name: CI

on:
  pull_request:
    types: [ opened, reopened, closed, converted_to_draft]
    branches:
      - 'main'

permissions:
  checks: read
  actions: read

jobs:
  checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install & Build
        run: npm install
             npm run build
      - uses: ./
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: prakrit55/githubactions

  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install & Build
        run: npm install
             npm run build
      - uses: ./
        with:
          jobs: 'pr-merged'
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: prakrit55/githubactions