name: CI

on:
  pull_request_target:
    types: [ opened, reopened, closed, converted_to_draft]
    branches:
      - 'main'

permissions:
  checks: read
  actions: read

jobs:
  checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: npm install
      - run: npm run build
      - uses: ./
        with:
          github-token: "${{ secrets.MY_NEW_GITHUB_TOKEN_APP }}"

  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install & Build
        run: npm install
             npm run build
      - uses: ./
        with:
          github-token: "${{ secrets.MY_NEW_GITHUB_TOKEN_APP }}"