name: PR has a valid Issue?

on:
  pull_request:
    types: [ opened, reopened, closed ]

jobs:
  checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Install & Build
        run: npm install
             npm run build

      - uses: ./
        with:
          github-token: ${{ secrets.MY_NEW_GITHUB_TOKEN_APP }} 