name: PR has a valid Issue?

on:
  pull_request:
    types: [ opened, reopened, closed ]
permissions: read-all
jobs:
  checker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - uses: ./
        with:
          github-token: "${{ secrets.MY_NEW_GITHUB_TOKEN_APP }}"