name: "Run Jobs on PR"
on: 
  pull_request:
    types: [opened]

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
      - uses: ./
        with:
          jobs: 'lgtm'
          github-token: "${{ secrets.MY_NEW_GITHUB_TOKEN_APP }}"
